### ISSUE TITLE
Change package ansible-language-server to @ansible/ansible-language-server?

### ISSUE THREAD

**Issue by yaegassy** [yaegassy/coc-ansible#2]
Ref: https://github.com/ansible/ansible-language-server/pull/10

It looks like it has not been published to npm yet.

**Comment by ganeshrn** [comment]
@yaegassy The work is in progress. Linking the right PR https://github.com/ansible/ansible-language-server/pull/18
After @ansible/ansible-language-server is published we will deprecate the `ansible-language-server` package.

**Comment by yaegassy** [comment]
@ganeshrn Thanks for the info!!!

**Comment by yaegassy** [comment]
I've seen `@ansible/ansible-language-server` released, but it's currently in beta (`v0.2.2-beta`).

**Comment by webknjaz** [comment]
I think we'll release v0.2.3 soon'ish.

**Comment by yaegassy** [comment]
@webknjaz By the way, I would like to confirm one thing. 

If `ansible-lint` is not installed in the Python environment, for some reason, the "ansible-playbook" `--syntax-check` error is output. https://github.com/yaegassy/coc-ansible/issues/8#issue-1022310383

Why does `ansible-playbook` output an error if `ansible-lint` is not present?

Is this a problem only with my extension? Is this a problem that is not reproduced by vscode-ansible?

**Comment by yaegassy** [comment]
@webknjaz Thanks for the explanation. I understand now. 

However, this is a file on the "role" side, not the "playbook". Do you mean to run `--syntax-check` on the role-side YAML file as well?

**Comment by webknjaz** [comment]
That one is probably a bug. I think @priyamsahoo is currently working on adding some heuristics for identifying whether something is a playbook or just a list of the role tasks. This was mentioned in #ansible-devtools on IRC/Matrix earlier today but I'm not sure if there's a formal issue yet.
