### ISSUE TITLE
Question: how to pass the current file as argument to ansible-lint?

### ISSUE THREAD

**Issue by nbn22385** [yaegassy/coc-ansible#23]
When i save a file, I would like ansible-lint to only scan the current file I have open in the editor.

It seems like I would need to supply an argument to `ansible.ansibleLint.arguments`, but I don't know how to accomplish this in my `coc-settings.json` file. Any ideas?

**Comment by yaegassy** [comment]
The ansible-lint executed when saving a file is internally executed with the following arguments. I believe only the current file is already running by default.

```
ansible-lint  --offline --nocolor -f codeclimate "/PATH/TO/ANSIBLEPROJECT/roles/xxx/tasks/main.yml"
```

Does it run at the workspace level (project level) in your environment? Please let me know how to reproduce this as I cannot reproduce it in my environment.

**Comment by nbn22385** [comment]
Ok you may be right. It seemed like it was running a little slow for me and I assumed the default value of `""` for the arguments mean the same as running `ansible-lint` with no arguments on the command line. How can i show debug output for what command is running?

**Comment by yaegassy** [comment]
There does not seem to be any debugging configuration for `ansible-lint` provided by [ansible-language-server](https://github.com/ansible/ansible-language-server).

It is possible to intentionally generate an error and see the command executed.

<img width="786" alt="coc-ansible-issue-23-1" src="https://user-images.githubusercontent.com/188642/183225146-9bca0ac5-6217-4d4a-a8de-bb4d7dd4d905.png">
