### ISSUE TITLE
Issue of getting it to work.

### ISSUE THREAD

**Issue by sojjan1337** [yaegassy/coc-ansible#30]
Hi!

Using neovim and i tried with ":CocInstall @yaegassy/coc-ansible" and also by adding the plugin and install it.
But when i edit a .yaml or .yml i can't get the auto-completion to work.

Also added the let g: code into my init.vim, and using  "Plug 'https://github.com/neoclide/coc.nvim"

i have ansible/lint/yamllint installed

Is there a good way to troubleshot this?

Thanks!

**Comment by yaegassy** [comment]
Is `filetype` set to `yaml.ansible`? `:set filetype?` to check filetype.

Also review the following README sections.

- <https://github.com/yaegassy/coc-ansible#-very-important--filetype-related>

**Comment by yaegassy** [comment]
For the installation of "coc.nvim" itself, check the following. An example is given for the case where the package manager is `vim-plug`.

```
Plug 'neoclide/coc.nvim', {'branch': 'release'}
```

- <https://github.com/neoclide/coc.nvim#quick-start>

**Comment by sojjan1337** [comment]
Works now when i :set filetype=yaml.ansible

But i thought that init.vim would do this by the let g: code?

Thanks! :)

**Comment by yaegassy** [comment]
Also check the README for `ansible-vim` if necessary. <https://github.com/pearofducks/ansible-vim#readme>

**Comment by sojjan1337** [comment]
au BufNewFile,BufRead *.yaml :setl ft=yaml.ansible
au BufNewFile,BufRead *.yml :setl ft=yaml.ansible
